import { adminHtml as baseAdminHtml } from "./admin-ui-v2";

const CURRENT_ACTIONS_OLD = `<div class="menuwrap"><button class="btn secondary" id="more">More</button><div class="menu" id="moremenu"><button class="red" id="clearall" disabled>Check everyone out…</button><button id="openkiosk">Open kiosk in new tab</button></div></div>`;
const CURRENT_ACTIONS_NEW = `<button class="btn" id="clearall" disabled>Check everyone out</button><div class="menuwrap"><button class="btn secondary" id="more">More</button><div class="menu" id="moremenu"><button id="openkiosk">Open kiosk in new tab</button></div></div>`;

const SYSTEM_NAV = `<div class="navgroup"><div class="navtitle">SYSTEM</div>`;
const STATS_NAV = `<div class="navgroup"><div class="navtitle">INSIGHTS</div><nav class="nav"><button class="navbtn" data-page="stats"><span class="icon"><svg viewBox="0 0 24 24"><path d="M4 20V10"/><path d="M10 20V4"/><path d="M16 20v-7"/><path d="M22 20V8"/></svg></span><span class="navlabel">Stats</span></button></nav></div>\n  ${SYSTEM_NAV}`;

const STATS_CSS = `
.statsbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.seg{display:flex;align-items:center;padding:3px;border:1px solid var(--line);border-radius:8px;background:#ebe7e1}.seg button{min-height:30px;padding:0 10px;border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:11.5px;font-weight:620}.seg button:hover{color:var(--ink)}.seg button.active{background:#fff;color:var(--ink);box-shadow:0 1px 2px rgba(40,34,29,.08)}.rangebox{display:none;align-items:end;gap:8px}.rangebox.open{display:flex}.rangetext{color:var(--muted);font-size:11.5px;white-space:nowrap}
.statstrip{display:grid;grid-template-columns:repeat(4,1fr);margin-bottom:18px;border:1px solid var(--line);border-radius:9px;background:#fff}.statcell{min-height:92px;display:grid;align-content:center;padding:15px 17px}.statcell+.statcell{border-left:1px solid var(--line)}.statcell b{font-size:27px;line-height:1;letter-spacing:-.04em}.statcell span{margin-top:7px;color:var(--muted);font-size:11.5px}.statcell:first-child b{color:var(--accent);font-size:32px}
.statsgrid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px}.chartpad{padding:15px}.trafficwrap{min-height:285px}.traffic-svg{display:block;width:100%;height:265px}.chartempty{min-height:210px;display:grid;place-items:center;color:var(--muted);font-size:12px}.chartlegend{display:flex;justify-content:space-between;gap:10px;margin-top:3px;color:var(--quiet);font-size:10.5px}.compare{color:var(--muted);font-size:11.5px}.compare strong{color:var(--ink)}
.bars{display:grid;gap:10px}.barrow{display:grid;grid-template-columns:100px minmax(0,1fr) 42px;align-items:center;gap:10px}.barlabel{overflow:hidden;color:var(--muted);font-size:11.5px;text-overflow:ellipsis;white-space:nowrap}.bartrack{height:8px;overflow:hidden;border-radius:3px;background:#efede9}.barfill{height:100%;min-width:1px;border-radius:3px;background:var(--accent)}.barval{color:var(--muted);text-align:right;font-size:11px;font-variant-numeric:tabular-nums}.barfill.neutral{background:#77716b}
.factgrid{display:grid;grid-template-columns:repeat(3,1fr)}.fact{min-height:94px;padding:14px 15px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.fact:nth-child(3n){border-right:0}.fact b{display:block;font-size:16px;letter-spacing:-.02em}.fact span{display:block;margin-top:5px;color:var(--muted);font-size:11.5px;line-height:1.35}.fact small{display:block;margin-top:7px;color:var(--quiet);font-size:10.5px}
.visitorstrip{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--line)}.visitorstat{padding:13px 15px}.visitorstat+.visitorstat{border-left:1px solid var(--line)}.visitorstat b{display:block;font-size:19px}.visitorstat span{display:block;margin-top:4px;color:var(--muted);font-size:10.5px}.regular{display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:52px;padding:7px 14px;border-bottom:1px solid var(--line);cursor:pointer}.regular:last-child{border-bottom:0}.regular:hover{background:#fbfaf8}.rank{color:var(--quiet);font-size:11px;font-variant-numeric:tabular-nums}.regname{font-size:12.5px;font-weight:650}.regmeta{margin-top:2px;color:var(--muted);font-size:10.5px}.regcount{text-align:right}.regcount b{display:block;font-size:13px}.regcount span{color:var(--quiet);font-size:10.5px}
.milestonegrid{display:grid;grid-template-columns:1fr 1fr}.milestonecol{padding:15px}.milestonecol+.milestonecol{border-left:1px solid var(--line)}.progress{height:8px;overflow:hidden;margin:10px 0 6px;border-radius:3px;background:#ece8e2}.progress span{display:block;height:100%;background:var(--accent)}.progressmeta{display:flex;justify-content:space-between;color:var(--muted);font-size:10.5px}.milestonelist{margin-top:13px;border-top:1px solid var(--line)}.mile{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:40px;border-bottom:1px solid var(--line);font-size:11.5px}.mile:last-child{border-bottom:0}.mile span:last-child{color:var(--quiet);font-size:10.5px}
@media(max-width:900px){.statstrip{grid-template-columns:1fr 1fr}.statcell:nth-child(3){border-left:0;border-top:1px solid var(--line)}.statcell:nth-child(4){border-top:1px solid var(--line)}.statsgrid{grid-template-columns:1fr}.factgrid{grid-template-columns:1fr 1fr}.fact:nth-child(3n){border-right:1px solid var(--line)}.fact:nth-child(2n){border-right:0}.visitorstrip{grid-template-columns:1fr 1fr}.visitorstat:nth-child(3){border-left:0;border-top:1px solid var(--line)}.visitorstat:nth-child(4){border-top:1px solid var(--line)}}
@media(max-width:700px){.statsbar{align-items:flex-start;flex-direction:column}.seg{max-width:100%;overflow:auto}.rangebox.open{align-items:stretch;flex-wrap:wrap}.statstrip,.visitorstrip{grid-template-columns:1fr}.statcell+.statcell,.visitorstat+.visitorstat{border-left:0;border-top:1px solid var(--line)}.factgrid{grid-template-columns:1fr}.fact{border-right:0!important}.milestonegrid{grid-template-columns:1fr}.milestonecol+.milestonecol{border-left:0;border-top:1px solid var(--line)}.barrow{grid-template-columns:82px minmax(0,1fr) 36px}}
`;

const STATS_PAGE = `
<section class="page" id="stats"><div class="work">
  <div class="statsbar">
    <div class="seg" id="statpresets">
      <button data-range="today">Today</button><button data-range="week">This week</button><button class="active" data-range="month">This month</button><button data-range="school">School year</button><button data-range="custom">Custom</button>
    </div>
    <div class="rangetext" id="statsrangetext">This month</div>
  </div>
  <div class="rangebox" id="statscustom"><div class="field"><label>From</label><input type="date" id="statsfrom"></div><div class="field"><label>To</label><input type="date" id="statsto"></div><button class="btn secondary" id="statsapply">Apply</button></div>

  <div class="statstrip">
    <div class="statcell"><b id="statvisits">—</b><span>visits</span></div>
    <div class="statcell"><b id="statunique">—</b><span>unique students</span></div>
    <div class="statcell"><b id="statpeak">—</b><span>peak occupancy</span></div>
    <div class="statcell"><b id="statmedian">—</b><span>median visit</span></div>
  </div>

  <section class="section"><div class="head"><div><strong>Library traffic</strong><div class="meta" id="trafficnote">Visits over time</div></div><div class="compare" id="trafficcompare"></div></div><div class="chartpad trafficwrap" id="trafficchart"></div></section>

  <div class="statsgrid">
    <section class="section"><div class="head"><div><strong>When students visit</strong><div class="meta" id="rushnote">Visits by time of day</div></div></div><div class="chartpad"><div class="bars" id="hourbars"></div></div></section>
    <section class="section"><div class="head"><div><strong>Days of the week</strong><div class="meta" id="weekdaynote">Which days are busiest</div></div></div><div class="chartpad"><div class="bars" id="weekdaybars"></div></div></section>
  </div>

  <div class="statsgrid">
    <section class="section"><div class="head"><div><strong>Why students visit</strong><div class="meta" id="reasonnote">Reasons selected at check-in</div></div></div><div class="chartpad"><div class="bars" id="reasonbars"></div></div></section>
    <section class="section"><div class="head"><div><strong>Grade levels</strong><div class="meta" id="gradenote">Visits by grade</div></div></div><div class="chartpad"><div class="bars" id="gradebars"></div></div></section>
  </div>

  <section class="section" style="margin-top:18px"><div class="head"><div><strong>Patterns & useful facts</strong><div class="meta">A few things worth knowing about this period</div></div></div><div class="factgrid" id="factgrid"></div></section>

  <div class="statsgrid">
    <section class="section"><div class="head"><div><strong>Visitors</strong><div class="meta">New, returning, and repeat library use</div></div></div><div class="visitorstrip"><div class="visitorstat"><b id="returnrate">—</b><span>returning visitors</span></div><div class="visitorstat"><b id="repeatrate">—</b><span>visited more than once</span></div><div class="visitorstat"><b id="regularcount">—</b><span>students with 5+ visits</span></div><div class="visitorstat"><b id="fivedaycount">—</b><span>students on 5+ days</span></div></div><div class="chartpad"><div class="bars" id="visitorbars"></div></div></section>
    <section class="section"><div class="head"><div><strong>Regulars</strong><div class="meta">Frequent visitors in this period</div></div></div><div id="regularlist"></div></section>
  </div>

  <section class="section" style="margin-top:18px"><div class="head"><div><strong>School year</strong><div class="meta" id="schoolnote">Progress and milestones</div></div></div><div class="milestonegrid"><div class="milestonecol"><strong id="schoolvisits">— visits</strong><div class="progress"><span id="visitprogress" style="width:0%"></span></div><div class="progressmeta"><span id="visitprogressnow"></span><span id="visitprogressnext"></span></div></div><div class="milestonecol"><strong id="schoolstudents">— students served</strong><div class="progress"><span id="studentprogress" style="width:0%"></span></div><div class="progressmeta"><span id="studentprogressnow"></span><span id="studentprogressnext"></span></div></div></div><div class="milestonelist" id="milestones"></div></section>
</div></section>
`;

const STATS_SCRIPT = `
<script>
pages.stats=['Stats','Useful patterns, traffic, and library milestones.'];
let statsPreset='month',statsData=null;
const statsDateFmt=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric'});
function statsToday(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),m={};p.forEach(x=>m[x.type]=x.value);return m.year+'-'+m.month+'-'+m.day}
function statsAddDate(v,n){const a=v.split('-').map(Number),d=new Date(Date.UTC(a[0],a[1]-1,a[2]));d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function statsRange(p){const t=statsToday(),a=t.split('-').map(Number);if(p==='today')return{from:t,to:t,label:'Today'};if(p==='week'){const d=new Date(Date.UTC(a[0],a[1]-1,a[2])),w=d.getUTCDay(),shift=w===0?-6:1-w;return{from:statsAddDate(t,shift),to:t,label:'This week'}}if(p==='school')return{from:(a[1]>=8?a[0]:a[0]-1)+'-08-01',to:t,label:'School year'};if(p==='custom'){return{from:$('statsfrom').value||t,to:$('statsto').value||t,label:'Custom range'}}return{from:t.slice(0,7)+'-01',to:t,label:'This month'}}
function statsPrettyDate(v){if(!v)return'—';const a=v.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(Date.UTC(a[0],a[1]-1,a[2])))}
function statsHour(h){if(h==null)return'—';const s=h>=12?'PM':'AM',x=h%12||12;return x+' '+s}
function statsDuration(m){if(m==null)return'—';if(m<60)return Math.round(m)+' min';const h=Math.floor(m/60),r=Math.round(m%60);return h+' hr'+(h===1?'':'s')+(r?' '+r+' min':'')}
function statsPercent(v){return (Number(v||0)%1?Number(v).toFixed(1):Number(v).toFixed(0))+'%'}
function setStatsPreset(p){statsPreset=p;document.querySelectorAll('#statpresets button').forEach(b=>b.classList.toggle('active',b.dataset.range===p));$('statscustom').classList.toggle('open',p==='custom');if(p!=='custom')loadStats()}
async function loadStats(){const r=statsRange(statsPreset);if(r.from>r.to){toast('Start date must be before end date.');return}$('statsrangetext').textContent=r.label==='Custom range'?statsPrettyDate(r.from)+' – '+statsPrettyDate(r.to):r.label;try{const d=await api('/api/library/admin-stats?from='+encodeURIComponent(r.from)+'&to='+encodeURIComponent(r.to));statsData=d;renderStats(d)}catch(e){toast(e.message)}}
function renderStats(d){const s=d.summary||{},v=d.visitors||{},p=d.patterns||{},l=d.lunch||{};$('statvisits').textContent=s.visits??0;$('statunique').textContent=s.uniqueStudents??0;$('statpeak').textContent=s.peakOccupancy??0;$('statmedian').textContent=statsDuration(s.medianDurationMinutes);$('trafficnote').textContent=(d.traffic&&d.traffic.granularity==='week'?'Weekly':'Daily')+' visits · '+statsPrettyDate(d.range.from)+' – '+statsPrettyDate(d.range.to);$('trafficcompare').innerHTML=statsCompare(s.visitChange,s.previousVisits);renderTraffic((d.traffic&&d.traffic.points)||[]);renderBars('hourbars',d.hourly||[],x=>x.label,x=>x.visits);renderBars('weekdaybars',(d.weekdays||[]).filter(x=>x.visits>0),x=>x.label,x=>x.visits,true);renderBars('reasonbars',d.reasons||[],x=>x.label,x=>x.visits);renderBars('gradebars',d.grades||[],x=>x.label==='Not set'?'Grade not set':'Grade '+x.label,x=>x.visits,true);$('rushnote').textContent=p.rushHour?('Rush hour '+ft(p.rushHour.startAt)+'–'+ft(p.rushHour.endAt)+' · '+p.rushHour.checkIns+' check-ins'):'Visits by time of day';$('weekdaynote').textContent=p.busiestWeekday?p.busiestWeekday.weekday+' is busiest in this period':'Which days are busiest';$('reasonnote').textContent=p.favoriteReason?(p.favoriteReason.reason+' leads with '+statsPercent(p.favoriteReason.share)+' of visits'):'Reasons selected at check-in';$('gradenote').textContent=p.topGrade?('Grade '+p.topGrade.grade+' visited most'):'Visits by grade';renderFacts(d);$('returnrate').textContent=statsPercent(v.returningRate);$('repeatrate').textContent=statsPercent(v.repeatRate);$('regularcount').textContent=v.regularCount||0;$('fivedaycount').textContent=v.fiveDayVisitors||0;renderBars('visitorbars',[{label:'Returning',visits:v.returningStudents||0},{label:'First-time',visits:v.firstTimeStudents||0}],x=>x.label,x=>x.visits,true);renderRegulars(v.regulars||[]);renderSchoolYear(d.schoolYear||{})}
function statsCompare(change,previous){change=Number(change||0);if(previous==null)return'';if(change===0)return'<strong>Same number of visits</strong> as the previous period';return'<strong>'+Math.abs(change)+' '+(change>0?'more':'fewer')+' visits</strong> than the previous period'}
function renderTraffic(points){const root=$('trafficchart');if(!points.length){root.innerHTML='<div class="chartempty">No visits in this period.</div>';return}const W=980,H=260,L=38,R=12,T=13,B=32,max=Math.max(1,...points.map(x=>Number(x.visits||0))),innerW=W-L-R,innerH=H-T-B,x=i=>L+(points.length===1?innerW/2:(i/(points.length-1))*innerW),y=n=>T+innerH-(n/max)*innerH;let grid='',labels='';for(let i=0;i<=4;i++){const val=Math.round((max/4)*i),yy=y(val);grid+='<line x1="'+L+'" y1="'+yy+'" x2="'+(W-R)+'" y2="'+yy+'" stroke="#e3dfd9" stroke-width="1"/><text x="'+(L-8)+'" y="'+(yy+3)+'" text-anchor="end" font-size="10" fill="#8d8a86">'+val+'</text>'}const path=points.map((q,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(Number(q.visits||0)).toFixed(1)).join(' '),step=Math.max(1,Math.ceil(points.length/6));points.forEach((q,i)=>{if(i%step===0||i===points.length-1)labels+='<text x="'+x(i)+'" y="'+(H-7)+'" text-anchor="middle" font-size="10" fill="#8d8a86">'+esc(q.label)+'</text>'});const dots=points.length<=35?points.map((q,i)=>'<circle cx="'+x(i)+'" cy="'+y(Number(q.visits||0))+'" r="2.7" fill="#74232d"><title>'+esc(q.label+': '+q.visits+' visits')+'</title></circle>').join(''):'';root.innerHTML='<svg class="traffic-svg" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="Library visits over time">'+grid+'<path d="'+path+'" fill="none" stroke="#74232d" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round"/>'+dots+labels+'</svg>'}
function renderBars(id,rows,labelFn,valueFn,neutral){const root=$(id);if(!rows.length){root.innerHTML='<div class="chartempty" style="min-height:120px">No data for this period.</div>';return}const max=Math.max(1,...rows.map(x=>Number(valueFn(x)||0)));root.innerHTML=rows.map(x=>{const val=Number(valueFn(x)||0),w=(val/max)*100;return'<div class="barrow"><div class="barlabel" title="'+esc(labelFn(x))+'">'+esc(labelFn(x))+'</div><div class="bartrack"><div class="barfill '+(neutral?'neutral':'')+'" style="width:'+w.toFixed(1)+'%"></div></div><div class="barval">'+val+'</div></div>'}).join('')}
function fact(value,label,note){return'<div class="fact"><b>'+esc(value)+'</b><span>'+esc(label)+'</span>'+(note?'<small>'+esc(note)+'</small>':'')+'</div>'}
function renderFacts(d){const s=d.summary||{},p=d.patterns||{},l=d.lunch||{},v=d.visitors||{},facts=[];facts.push(fact(String(s.averageDailyVisits||0),'average visits per active day'));facts.push(fact(statsDuration(s.averageDurationMinutes),'average completed visit'));facts.push(fact(p.rushHour?ft(p.rushHour.startAt)+'–'+ft(p.rushHour.endAt):'—','library rush hour',p.rushHour?p.rushHour.checkIns+' check-ins in 30 minutes · '+p.rushHour.perMinute+' per minute':''));facts.push(fact(p.busiestDate?statsPrettyDate(p.busiestDate.date):'—','busiest day',p.busiestDate?p.busiestDate.visits+' visits':''));facts.push(fact(p.busiestWeekday?p.busiestWeekday.weekday:'—','busiest weekday'));facts.push(fact(p.favoriteReason?p.favoriteReason.reason:'—','most common reason',p.favoriteReason?statsPercent(p.favoriteReason.share)+' of visits':''));facts.push(fact(p.topGrade?'Grade '+p.topGrade.grade:'—','most frequent grade'));facts.push(fact(p.busiestHour?statsHour(p.busiestHour.hour):'—','busiest hour'));facts.push(fact(p.quietestActiveHour?statsHour(p.quietestActiveHour.hour):'—','quietest active hour','Lowest non-zero traffic hour'));facts.push(fact(statsDuration(p.longestCompletedVisitMinutes),'longest completed visit'));facts.push(fact(String(l.visits||0),'lunch visits',l.peakOccupancy?'peak lunch occupancy '+l.peakOccupancy:''));facts.push(fact(statsDuration(l.medianDurationMinutes),'median lunch visit'));facts.push(fact(String(v.fiveDayVisitors||0),'students who visited on 5+ days'));$('factgrid').innerHTML=facts.join('')}
function renderRegulars(rows){const root=$('regularlist');if(!rows.length){root.innerHTML='<div class="good">No one has five visits in this period yet.</div>';return}root.innerHTML=rows.map((r,i)=>'<div class="regular" data-id="'+esc(r.studentRowId)+'" tabindex="0"><div class="rank">'+(i+1)+'</div><div><div class="regname">'+esc(r.firstName+' '+r.lastName)+'</div><div class="regmeta">'+esc((r.grade?'Grade '+r.grade+' · ':'')+r.daysVisited+' day'+(r.daysVisited===1?'':'s')+' visited')+'</div></div><div class="regcount"><b>'+r.visits+'</b><span>visits</span></div></div>').join('')}
function renderSchoolYear(s){$('schoolnote').textContent=s.start?statsPrettyDate(s.start)+' through '+statsPrettyDate(s.through):'Progress and milestones';$('schoolvisits').textContent=(s.visits||0)+' visits';$('schoolstudents').textContent=(s.uniqueStudents||0)+' students served';const nv=Math.max(Number(s.nextVisitMilestone||1),1),nu=Math.max(Number(s.nextUniqueMilestone||1),1);$('visitprogress').style.width=Math.min(100,(Number(s.visits||0)/nv)*100)+'%';$('studentprogress').style.width=Math.min(100,(Number(s.uniqueStudents||0)/nu)*100)+'%';$('visitprogressnow').textContent=(s.visits||0)+' so far';$('visitprogressnext').textContent='Next: '+nv;$('studentprogressnow').textContent=(s.uniqueStudents||0)+' so far';$('studentprogressnext').textContent='Next: '+nu;const rows=s.milestones||[];$('milestones').innerHTML=rows.length?rows.map(m=>'<div class="mile"><span>'+esc(m.value+(m.type==='visits'?' visits':' students served'))+'</span><span>'+esc(fdt(m.reachedAt))+'</span></div>').join(''):'<div class="good">The first school-year milestones are still ahead.</div>'}
$('statpresets').addEventListener('click',e=>{const b=e.target.closest('button[data-range]');if(b)setStatsPreset(b.dataset.range)});$('statsapply').addEventListener('click',()=>loadStats());$('regularlist').addEventListener('click',e=>{const r=e.target.closest('.regular');if(r)studentDetail(r.dataset.id)});$('regularlist').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.regular')){e.preventDefault();studentDetail(e.target.closest('.regular').dataset.id)}});$('refresh').addEventListener('click',()=>{if(state.page==='stats')loadStats()});document.querySelector('[data-page="stats"]').addEventListener('click',()=>loadStats());const initialStatsHash=location.hash.slice(1)==='stats';if(initialStatsHash){setPage('stats');loadStats()}
</script>
`;

export function adminHtml(): string {
  return baseAdminHtml()
    .replace(CURRENT_ACTIONS_OLD, CURRENT_ACTIONS_NEW)
    .replace(SYSTEM_NAV, STATS_NAV)
    .replace("</style>", STATS_CSS + "</style>")
    .replace('<section class="page" id="kiosks">', STATS_PAGE + '<section class="page" id="kiosks">')
    .replace("</body>", STATS_SCRIPT + "</body>");
}
