export function adminHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Library · Flow</title>
<style>
:root{color-scheme:light;--bg:#f4f2ee;--side:#eeeae4;--surface:#fff;--subtle:#f8f7f4;--ink:#202022;--muted:#686765;--quiet:#8d8a86;--line:#d9d4cd;--line2:#c9c2ba;--accent:#74232d;--accentSoft:#f4e9eb;--green:#27633f;--greenSoft:#edf5ef;--amber:#8a5a12;--amberSoft:#fbf2df;--red:#a3323b;--redSoft:#f9e9eb;--sideW:214px;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink)}body{-webkit-font-smoothing:antialiased}button,input,select{font:inherit}button{cursor:pointer}
.app{min-height:100vh;display:grid;grid-template-columns:var(--sideW) minmax(0,1fr)}.sidebar{position:fixed;inset:0 auto 0 0;width:var(--sideW);z-index:20;display:flex;flex-direction:column;padding:20px 12px 14px;background:var(--side);border-right:1px solid var(--line)}
.brand{display:flex;align-items:center;gap:10px;min-height:48px;padding:0 10px 18px}.brandbar{width:4px;height:31px;border-radius:2px;background:var(--accent)}.brand strong{display:block;font-size:16px;letter-spacing:-.02em}.brand span{display:block;margin-top:3px;color:var(--muted);font-size:11.5px}
.navgroup{margin-bottom:17px}.navtitle{padding:0 10px 6px;color:var(--quiet);font-size:10px;font-weight:720;letter-spacing:.08em}.nav{display:grid;gap:2px}.navbtn{min-height:38px;display:flex;align-items:center;gap:9px;padding:0 9px;border:0;border-radius:7px;background:transparent;color:#42403d;text-align:left;font-size:13.5px;font-weight:560}.navbtn:hover{background:rgba(0,0,0,.045)}.navbtn.active{background:#fff;color:var(--accent);box-shadow:0 0 0 1px rgba(116,35,45,.08);font-weight:650}
.icon{width:18px;height:18px;display:grid;place-items:center;flex:0 0 auto}.icon svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.badge{margin-left:auto;min-width:23px;height:21px;display:grid;place-items:center;padding:0 6px;border-radius:10px;background:rgba(0,0,0,.055);color:var(--muted);font-size:11px;font-weight:700}.navbtn.active .badge{background:var(--accentSoft);color:var(--accent)}
.sidefill{flex:1}.sidefoot{padding:12px 6px 0;border-top:1px solid var(--line)}.sidefoot a{min-height:34px;display:flex;align-items:center;gap:8px;padding:0 6px;border-radius:6px;color:var(--muted);text-decoration:none;font-size:12.5px}.sidefoot a:hover{background:rgba(0,0,0,.04);color:var(--ink)}
.main{grid-column:2;min-width:0}.top{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 28px;border-bottom:1px solid var(--line)}h1{margin:0;font-size:23px;letter-spacing:-.035em}.subtitle{margin-top:4px;color:var(--muted);font-size:12.5px}.live{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:12px}.dot{width:7px;height:7px;border-radius:50%;background:var(--green)}.refresh{min-height:30px;padding:0 7px;border:0;border-radius:6px;background:transparent;color:var(--muted);font-size:12px;font-weight:600}.refresh:hover{background:rgba(0,0,0,.045);color:var(--ink)}
.page{display:none;padding:24px 28px 36px}.page.active{display:block}.work{width:min(1280px,100%)}.btn{min-height:36px;padding:0 13px;border:1px solid var(--accent);border-radius:7px;background:var(--accent);color:#fff;font-size:13px;font-weight:650}.btn.secondary{border-color:var(--line2);background:#fff;color:var(--ink)}.btn.ghost{border-color:transparent;background:transparent;color:var(--accent)}.btn.danger{border-color:var(--red);background:var(--red)}.btn.dangerquiet{border-color:transparent;background:transparent;color:var(--red)}.btn.small{min-height:30px;padding:0 9px;font-size:12px}.btn:disabled{opacity:.45;cursor:not-allowed}
.section{overflow:hidden;border:1px solid var(--line);border-radius:9px;background:#fff}.section+.section{margin-top:18px}.head{min-height:52px;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 15px;border-bottom:1px solid var(--line)}.head strong{font-size:14px}.meta{margin-top:3px;color:var(--muted);font-size:11.5px}
.summary{display:grid;grid-template-columns:1.25fr .75fr .75fr;margin-bottom:18px;border:1px solid var(--line);border-radius:9px;background:#fff}.sum{min-height:98px;display:grid;align-content:center;padding:17px 19px}.sum+.sum{border-left:1px solid var(--line)}.sum b{font-size:28px;line-height:1;letter-spacing:-.04em}.sum:first-child b{color:var(--accent);font-size:34px}.sum span{margin-top:7px;color:var(--muted);font-size:12px}.overviewgrid{display:grid;grid-template-columns:1.35fr .65fr;gap:18px;align-items:start}
.list{display:grid}.item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:11px 15px;border-bottom:1px solid var(--line)}.item:last-child{border-bottom:0}.itemname{font-size:12.5px;font-weight:650}.itemsub{margin-top:3px;color:var(--muted);font-size:11.5px;line-height:1.3}.itemtime{color:var(--quiet);font-size:11px;white-space:nowrap}.attention{grid-template-columns:20px minmax(0,1fr) auto;align-items:center}.warn{width:18px;height:18px;display:grid;place-items:center;border-radius:50%;background:var(--amberSoft);color:var(--amber);font-size:12px;font-weight:800}.good{min-height:88px;display:flex;align-items:center;gap:10px;padding:0 15px;color:var(--muted);font-size:12.5px}.goodmark{width:24px;height:24px;display:grid;place-items:center;border-radius:50%;background:var(--greenSoft);color:var(--green);font-weight:800}
.toolbar{display:flex;align-items:center;gap:9px;margin-bottom:12px}.push{margin-right:auto}.search{position:relative;flex:1 1 300px;min-width:220px}.search:before{content:"⌕";position:absolute;left:11px;top:50%;transform:translateY(-53%);color:var(--quiet);font-size:18px}.search input{width:100%;padding-left:32px}input,select{min-height:36px;border:1px solid var(--line2);border-radius:7px;background:#fff;color:var(--ink);padding:0 10px;outline:none;font-size:12.5px}input:focus,select:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(116,35,45,.09)}
.tablewrap{overflow:auto}table{width:100%;min-width:760px;border-collapse:collapse}th{height:34px;padding:0 13px;border-bottom:1px solid var(--line);background:var(--subtle);color:var(--quiet);text-align:left;font-size:10px;font-weight:720;letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}td{height:54px;padding:8px 13px;border-bottom:1px solid var(--line);color:#3f3d3a;font-size:12.5px;vertical-align:middle}tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:#fbfaf8}.person{color:var(--ink);font-size:13px;font-weight:670}.secondaryline{margin-top:3px;color:var(--quiet);font-size:11px}.mono{font-variant-numeric:tabular-nums}.clickrow{cursor:pointer}td.rowaction{width:1%;text-align:right;white-space:nowrap}
.status{display:inline-flex;align-items:center;gap:7px;color:var(--muted);font-size:12px}.status:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--quiet)}.status.ok{color:var(--green)}.status.ok:before{background:var(--green)}.status.warns{color:var(--amber)}.status.warns:before{background:var(--amber)}
.empty{min-height:220px;display:grid;place-items:center;padding:28px;color:var(--muted);text-align:center;font-size:12.5px}.empty[hidden]{display:none}.empty strong{display:block;margin-bottom:5px;color:var(--ink);font-size:13.5px}.pager{min-height:46px;display:flex;align-items:center;justify-content:space-between;padding:7px 12px;border-top:1px solid var(--line);color:var(--muted);font-size:11.5px}
.menuwrap{position:relative}.menu{position:absolute;top:calc(100% + 5px);right:0;z-index:12;width:190px;display:none;padding:5px;border:1px solid var(--line2);border-radius:8px;background:#fff;box-shadow:0 10px 28px rgba(40,34,29,.12)}.menu.open{display:grid}.menu button{min-height:34px;padding:0 9px;border:0;border-radius:5px;background:transparent;color:var(--ink);text-align:left;font-size:12.5px}.menu button:hover{background:var(--subtle)}.menu .red{color:var(--red)}
.filters{display:none;margin:-2px 0 12px;padding:11px;border:1px solid var(--line);border-radius:8px;background:#efede9}.filters.open{display:flex;align-items:end;gap:9px;flex-wrap:wrap}.field{display:grid;gap:5px}.field label{color:var(--muted);font-size:10.5px;font-weight:650}.field input,.field select{width:100%}
.device{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:center;padding:14px 15px;border-bottom:1px solid var(--line)}.device:last-child{border-bottom:0}.devname{font-size:13px;font-weight:670}.devmeta{margin-top:4px;color:var(--muted);font-size:11.5px}.devactions{display:flex;align-items:center;gap:10px}
.scrim{position:fixed;inset:0;z-index:39;display:none;background:rgba(32,28,25,.18)}.scrim.open{display:block}.drawer{position:fixed;inset:0 0 0 auto;z-index:40;width:min(430px,calc(100vw - 24px));display:grid;grid-template-rows:auto minmax(0,1fr) auto;transform:translateX(100%);border-left:1px solid var(--line);background:#fff;box-shadow:-18px 0 44px rgba(40,34,29,.11);transition:transform .17s ease}.drawer.open{transform:translateX(0)}.drawerhead{min-height:70px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;border-bottom:1px solid var(--line)}.drawertitle{font-size:18px;font-weight:720}.drawersub{margin-top:4px;color:var(--muted);font-size:11.5px}.x{width:32px;height:32px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--muted);font-size:17px}.drawerbody{overflow:auto;padding:18px}.drawersection+.drawersection{margin-top:22px}.eyebrow{margin-bottom:10px;color:var(--muted);font-size:10.5px;font-weight:720;letter-spacing:.06em;text-transform:uppercase}.details{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);border-radius:8px;overflow:hidden}.detail{min-height:66px;padding:11px 12px;border-bottom:1px solid var(--line)}.detail:nth-child(odd){border-right:1px solid var(--line)}.detail:nth-last-child(-n+2){border-bottom:0}.detail small{display:block;color:var(--muted)}.detail b{display:block;margin-top:6px;font-size:12.5px}.draweractions{min-height:64px;display:flex;align-items:center;justify-content:flex-end;gap:9px;padding:0 18px;border-top:1px solid var(--line);background:var(--subtle)}.editform{display:none;gap:12px}.editform.open{display:grid}.twocol{display:grid;grid-template-columns:1fr 1fr;gap:10px}.check{display:flex;align-items:center;gap:8px;font-size:12.5px}.check input{width:16px;height:16px;min-height:0;accent-color:var(--accent)}
.modalbg{position:fixed;inset:0;z-index:50;display:none;place-items:center;padding:18px;background:rgba(32,28,25,.28)}.modalbg.open{display:grid}.modal{width:min(470px,100%);overflow:hidden;border:1px solid var(--line2);border-radius:10px;background:#fff;box-shadow:0 24px 70px rgba(40,34,29,.2)}.modalhead{min-height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;border-bottom:1px solid var(--line)}.modalbody{padding:16px}.modalactions{min-height:58px;display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:0 16px;border-top:1px solid var(--line);background:var(--subtle)}.paircopy,.confirmcopy{color:var(--muted);font-size:12.5px;line-height:1.45}.paircode{margin:14px 0 8px;padding:17px 12px;border:1px solid #c8d8cd;border-radius:8px;background:var(--greenSoft);color:var(--green);text-align:center;font-size:30px;font-weight:760;letter-spacing:.12em}.pairexp{color:var(--muted);text-align:center;font-size:11.5px}
.toast{position:fixed;right:20px;bottom:20px;z-index:80;min-width:210px;max-width:360px;padding:10px 12px;border-radius:7px;background:#2e2b29;color:#fff;box-shadow:0 12px 30px rgba(0,0,0,.18);font-size:12px;opacity:0;transform:translateY(6px);pointer-events:none;transition:.12s}.toast.show{opacity:1;transform:none}
@media(max-width:980px){:root{--sideW:72px}.sidebar{padding-left:8px;padding-right:8px}.brand{justify-content:center;padding-left:0;padding-right:0}.brandbar{width:5px}.brand div:last-child,.navtitle,.navlabel,.badge,.sidefoot .navlabel{display:none}.navbtn,.sidefoot a{justify-content:center;padding-left:0;padding-right:0}.top,.page{padding-left:18px;padding-right:18px}.overviewgrid{grid-template-columns:1fr}}
@media(max-width:700px){.subtitle{display:none}.summary{grid-template-columns:1fr}.sum+.sum{border-left:0;border-top:1px solid var(--line)}.toolbar{align-items:stretch;flex-wrap:wrap}.search{flex-basis:100%}.twocol,.details{grid-template-columns:1fr}.detail:nth-child(odd){border-right:0}.detail:nth-last-child(-n+2){border-bottom:1px solid var(--line)}.detail:last-child{border-bottom:0}}
</style>
</head>
<body>
<div class="app">
<aside class="sidebar">
  <div class="brand"><div class="brandbar"></div><div><strong>Flow</strong><span>Library</span></div></div>
  <div class="navgroup"><nav class="nav"><button class="navbtn" data-page="overview"><span class="icon"><svg viewBox="0 0 24 24"><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/></svg></span><span class="navlabel">Overview</span></button></nav></div>
  <div class="navgroup"><div class="navtitle">LIVE</div><nav class="nav"><button class="navbtn active" data-page="current"><span class="icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20v-1a6 6 0 0 1 12 0v1"/><path d="M17 6a3 3 0 0 1 0 6"/></svg></span><span class="navlabel">Current</span><span class="badge" id="sidecount">—</span></button></nav></div>
  <div class="navgroup"><div class="navtitle">RECORDS</div><nav class="nav">
    <button class="navbtn" data-page="students"><span class="icon"><svg viewBox="0 0 24 24"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span><span class="navlabel">Students</span></button>
    <button class="navbtn" data-page="history"><span class="icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><span class="navlabel">History</span></button>
  </nav></div>
  <div class="navgroup"><div class="navtitle">SYSTEM</div><nav class="nav"><button class="navbtn" data-page="kiosks"><span class="icon"><svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M8 21h8M12 17v4"/></svg></span><span class="navlabel">Kiosks</span></button></nav></div>
  <div class="sidefill"></div>
  <div class="sidefoot"><a href="/library/kiosk" target="_blank" rel="noopener"><span class="icon"><svg viewBox="0 0 24 24"><path d="M14 3h7v7"/><path d="M10 14 21 3"/><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></svg></span><span class="navlabel">Open kiosk</span></a></div>
</aside>

<main class="main">
<header class="top"><div><h1 id="pagetitle">Current</h1><div class="subtitle" id="pagesub">Students who are checked in right now.</div></div><div class="live"><span class="dot"></span><span id="updated">Live</span><button class="refresh" id="refresh">Refresh</button></div></header>

<section class="page" id="overview"><div class="work">
  <div class="summary">
    <div class="sum"><b id="ovcurrent">—</b><span>students in the library now</span></div>
    <div class="sum"><b id="ovvisits">—</b><span>visits today · <span id="ovunique">— unique</span></span></div>
    <div class="sum"><b id="ovkiosks">—</b><span>kiosks online · <span id="ovpaired">— paired</span></span></div>
  </div>
  <div class="overviewgrid">
    <section class="section"><div class="head"><div><strong>Recent activity</strong><div class="meta">Latest check-ins and checkouts</div></div><button class="btn ghost small" data-go="history">View history</button></div><div class="list" id="recent"></div></section>
    <section class="section"><div class="head"><div><strong>Needs attention</strong><div class="meta">Only items that may need a librarian</div></div></div><div class="list" id="attention"></div></section>
  </div>
</div></section>

<section class="page active" id="current"><div class="work">
  <div class="toolbar"><div class="push"><strong id="currentsummary">— in library</strong> <span class="meta" id="currentmeta">Live roster</span></div><div class="search"><input id="currentsearch" type="search" placeholder="Search current students"></div><div class="menuwrap"><button class="btn secondary" id="more">More</button><div class="menu" id="moremenu"><button class="red" id="clearall" disabled>Check everyone out…</button><button id="openkiosk">Open kiosk in new tab</button></div></div></div>
  <section class="section"><div class="tablewrap"><table><thead><tr><th>Student</th><th>Grade</th><th>Reason</th><th>Checked in</th><th>Time here</th><th></th></tr></thead><tbody id="currentbody"></tbody></table></div><div class="empty" id="currentempty" hidden><div><strong>No students are checked in.</strong>The roster will update when someone scans in.</div></div></section>
</div></section>

<section class="page" id="students"><div class="work">
  <div class="toolbar"><div class="search"><input id="studentsearch" type="search" placeholder="Search students"></div><select id="studentgrade"><option value="">All grades</option><option>9</option><option>10</option><option>11</option><option>12</option></select><select id="studentstatus"><option value="">All records</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button class="btn" id="addstudent">Add student</button></div>
  <section class="section"><div class="head"><div><strong>Student directory</strong><div class="meta" id="studentnote">Loading records…</div></div></div><div class="tablewrap"><table><thead><tr><th>Student</th><th>Grade</th><th>Barcode</th><th>Visits</th><th>Last visit</th><th>Status</th><th></th></tr></thead><tbody id="studentbody"></tbody></table></div><div class="empty" id="studentempty" hidden><div><strong>No students found.</strong>Try a different search or filter.</div></div><div class="pager"><span id="studentpage"></span><div><button class="btn secondary small" id="studentprev">Previous</button> <button class="btn secondary small" id="studentnext">Next</button></div></div></section>
</div></section>

<section class="page" id="history"><div class="work">
  <div class="toolbar"><div class="search"><input id="historysearch" type="search" placeholder="Search visits"></div><select id="period"><option value="today">Today</option><option value="7" selected>Last 7 days</option><option value="30">Last 30 days</option><option value="custom">Custom dates</option></select><select id="archivedview"><option value="">Active records</option><option value="1">Archived records</option></select><button class="btn secondary" id="filterbtn">Filters</button><button class="btn secondary" id="exportbtn">Export</button></div>
  <div class="filters" id="filters"><div class="field"><label>Reason</label><select id="reason"><option value="">Any reason</option><option>Class work</option><option>Printing</option><option>Book checkout</option><option>Lunch</option><option>Meeting</option><option>Other</option></select></div><div class="field" id="fromfield" hidden><label>From</label><input id="from" type="date"></div><div class="field" id="tofield" hidden><label>To</label><input id="to" type="date"></div></div>
  <section class="section"><div class="head"><div><strong>Visit history</strong><div class="meta" id="historynote">Loading visits…</div></div></div><div class="tablewrap"><table><thead><tr><th>Student</th><th>Reason</th><th>Check in</th><th>Check out</th><th>Duration</th><th>Checkout</th><th></th></tr></thead><tbody id="historybody"></tbody></table></div><div class="empty" id="historyempty" hidden><div><strong id="historyemptytitle">No visits found.</strong><span id="historyemptycopy">Change the date range or filters.</span></div></div><div class="pager"><span id="historypage"></span><div><button class="btn secondary small" id="historyprev">Previous</button> <button class="btn secondary small" id="historynext">Next</button></div></div></section>
</div></section>

<section class="page" id="kiosks"><div class="work">
  <div class="toolbar"><div class="push"></div><button class="btn" id="pairbtn">Pair new kiosk</button></div>
  <section class="section"><div class="head"><div><strong>Kiosk devices</strong><div class="meta" id="kiosknote">Loading devices…</div></div></div><div id="kiosklist"></div><div class="empty" id="kioskempty" hidden><div><strong>No kiosks paired yet.</strong>Pair a Chromebook to start using the check-in kiosk.</div></div></section>
</div></section>
</main>
</div>

<div class="scrim" id="scrim"></div>
<aside class="drawer" id="drawer">
  <div class="drawerhead"><div><div class="drawertitle" id="drawertitle">Student</div><div class="drawersub" id="drawersub"></div></div><button class="x" id="drawerclose">×</button></div>
  <div class="drawerbody">
    <div id="drawerview">
      <div class="drawersection"><div class="eyebrow">Student information</div><div class="details"><div class="detail"><small>Grade</small><b id="dgrade">—</b></div><div class="detail"><small>Status</small><b id="dstatus">—</b></div><div class="detail"><small>Barcode</small><b class="mono" id="dbarcode">—</b></div><div class="detail"><small>Total visits</small><b id="dvisits">—</b></div></div></div>
      <div class="drawersection"><div class="eyebrow">Recent visits</div><div class="list" id="drecent"></div></div>
    </div>
    <form class="editform" id="studentform">
      <input id="editid" type="hidden">
      <div class="field"><label>Student ID</label><input id="sid" required maxlength="64"></div>
      <div class="twocol"><div class="field"><label>First name</label><input id="first" required maxlength="80"></div><div class="field"><label>Last name</label><input id="last" required maxlength="80"></div></div>
      <div class="twocol"><div class="field"><label>Barcode</label><input id="barcode" required maxlength="80"></div><div class="field"><label>Grade</label><select id="editgrade"><option value="">Not set</option><option>9</option><option>10</option><option>11</option><option>12</option></select></div></div>
      <label class="check"><input id="active" type="checkbox" checked> Active student record</label>
    </form>
  </div>
  <div class="draweractions"><button class="btn secondary" id="canceledit" hidden>Cancel</button><button class="btn secondary" id="editbtn">Edit</button><button class="btn" id="savebtn" hidden>Save student</button></div>
</aside>

<div class="modalbg" id="pairmodal"><div class="modal"><div class="modalhead"><strong>Pair a kiosk</strong><button class="x" id="pairclose">×</button></div><div class="modalbody"><div id="pairstart"><div class="paircopy">On the Chromebook, open the library kiosk. Give the device a recognizable name, then enter the one-time code on the Chromebook.</div><div class="field" style="margin-top:12px"><label>Device name</label><input id="kioskname" maxlength="80" placeholder="Front desk Chromebook"></div></div><div id="pairresult" hidden><div class="paircopy">Enter this code on the kiosk. It can only be used once.</div><div class="paircode" id="paircode"></div><div class="pairexp" id="pairexp"></div></div></div><div class="modalactions"><button class="btn secondary" id="paircancel">Cancel</button><button class="btn" id="generate">Generate code</button><button class="btn" id="pairdone" hidden>Done</button></div></div></div>

<div class="modalbg" id="confirmmodal"><div class="modal"><div class="modalhead"><strong id="confirmtitle">Confirm action</strong><button class="x" id="confirmclose">×</button></div><div class="modalbody"><div class="confirmcopy" id="confirmcopy"></div></div><div class="modalactions"><button class="btn secondary" id="confirmcancel">Cancel</button><button class="btn danger" id="confirmaction">Continue</button></div></div></div>
<div class="toast" id="toast"></div>

<script>
const $=id=>document.getElementById(id);
const pages={overview:['Overview','Today’s activity and anything that needs attention.'],current:['Current','Students who are checked in right now.'],students:['Students','Find a student or update a record.'],history:['History','Look up previous library visits.'],kiosks:['Kiosks','Pair and manage check-in devices.']};
const state={page:'current',current:[],students:[],studentOffset:0,studentTotal:0,history:[],historyOffset:0,historyTotal:0,pageSize:100,student:null,studentVisits:[],pairExpiry:0,pairTimer:0,confirm:null};
const dt=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const tm=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'});
let toastTimer=0,searchTimer=0,lastUpdated=0;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fdt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':dt.format(d)}
function ft(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':tm.format(d)}
function mins(a,b){const x=new Date(a).getTime(),y=new Date(b||Date.now()).getTime();return Number.isFinite(x)&&Number.isFinite(y)&&y>=x?Math.round((y-x)/60000):null}
function dur(m){if(m==null)return'—';if(m<60)return m+' min';const h=Math.floor(m/60),r=m%60;return h+' hr'+(h===1?'':'s')+(r?' '+r+' min':'')}
function ago(v){if(!v)return'never';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<1)return'just now';if(m<60)return m+' min ago';const h=Math.floor(m/60);if(h<24)return h+' hr'+(h===1?'':'s')+' ago';const d=Math.floor(h/24);return d+' day'+(d===1?'':'s')+' ago'}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function updated(){lastUpdated=Date.now();renderUpdated()}
function renderUpdated(){if(!lastUpdated){$('updated').textContent='Live';return}const s=Math.floor((Date.now()-lastUpdated)/1000);$('updated').textContent=s<10?'Live · updated just now':s<60?'Live · updated '+s+'s ago':'Live · updated '+Math.floor(s/60)+'m ago'}
async function api(url,o){const r=await fetch(url,Object.assign({cache:'no-store'},o||{}));const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');updated();return d}
function post(url,b){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{})})}
function setPage(p){if(!pages[p])return;state.page=p;document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));$('pagetitle').textContent=pages[p][0];$('pagesub').textContent=pages[p][1];history.replaceState(null,'','#'+p);loadPage(p)}
function loadPage(p){if(p==='overview')return loadOverview();if(p==='current')return loadCurrent();if(p==='students')return loadStudents();if(p==='history')return loadHistory();if(p==='kiosks')return loadKiosks()}
async function loadOverview(){try{const d=await api('/api/library/admin-overview');$('ovcurrent').textContent=d.currentCount;$('ovvisits').textContent=d.visitsToday;$('ovunique').textContent=d.uniqueVisitorsToday+' unique';$('ovkiosks').textContent=d.onlineKiosks;$('ovpaired').textContent=d.pairedKiosks+' paired';$('sidecount').textContent=d.currentCount;renderRecent(d.recent||[]);renderAttention(d.attention||{})}catch(e){toast(e.message)}}
function renderRecent(rows){$('recent').innerHTML=rows.length?rows.map(v=>'<div class="item"><div><div class="itemname">'+esc(v.firstName+' '+v.lastName)+'</div><div class="itemsub">'+esc(v.reason+' · '+(v.checkedOutAt?'Checked out':'In library')+(v.durationMinutes!=null?' · '+dur(v.durationMinutes):''))+'</div></div><div class="itemtime">'+esc(fdt(v.checkedInAt))+'</div></div>').join(''):'<div class="good">No activity yet today.</div>'}
function renderAttention(a){const out=[];(a.longVisits||[]).forEach(v=>out.push('<div class="item attention"><span class="warn">!</span><div><div class="itemname">'+esc(v.firstName+' '+v.lastName)+' has been checked in for '+esc(dur(mins(v.checkedInAt)))+'</div><div class="itemsub">'+esc(v.reason+' · checked in '+ft(v.checkedInAt))+'</div></div><button class="btn ghost small" data-go="current">View</button></div>'));(a.staleKiosks||[]).forEach(k=>out.push('<div class="item attention"><span class="warn">!</span><div><div class="itemname">'+esc(k.name)+' is offline</div><div class="itemsub">Last seen '+esc(ago(k.lastSeenAt))+'</div></div><button class="btn ghost small" data-go="kiosks">View</button></div>'));$('attention').innerHTML=out.length?out.join(''):'<div class="good"><span class="goodmark">✓</span>Everything looks good.</div>'}
async function loadCurrent(){try{const d=await api('/api/library/current');state.current=d.students||[];$('sidecount').textContent=d.currentCount;$('currentsummary').textContent=d.currentCount+' in library';$('currentmeta').textContent=d.currentCount===1?'1 student checked in':d.currentCount+' students checked in';$('clearall').disabled=d.currentCount===0;renderCurrent()}catch(e){toast(e.message)}}
function renderCurrent(){const q=$('currentsearch').value.trim().toLowerCase();const rows=state.current.filter(v=>!q||(v.firstName+' '+v.lastName+' '+v.studentId+' '+v.reason).toLowerCase().includes(q));$('currentempty').hidden=rows.length>0;$('currentbody').innerHTML=rows.map(v=>'<tr><td><div class="person">'+esc(v.firstName+' '+v.lastName)+'</div><div class="secondaryline">'+esc(v.studentId)+'</div></td><td>'+esc(v.grade||'—')+'</td><td>'+esc(v.reason)+'</td><td class="mono">'+esc(ft(v.checkedInAt))+'</td><td>'+esc(dur(mins(v.checkedInAt)))+'</td><td><button class="btn dangerquiet small checkout" data-id="'+esc(v.visitId)+'">Check out</button></td></tr>').join('')}
function studentQuery(){const p=new URLSearchParams({limit:String(state.pageSize),offset:String(state.studentOffset)}),q=$('studentsearch').value.trim(),g=$('studentgrade').value,s=$('studentstatus').value;if(q)p.set('q',q);if(g)p.set('grade',g);if(s)p.set('status',s);return p}
async function loadStudents(){try{const d=await api('/api/library/admin-students?'+studentQuery());state.students=d.students||[];state.studentTotal=d.total||0;$('studentnote').textContent=state.studentTotal+' student record'+(state.studentTotal===1?'':'s');$('studentempty').hidden=state.students.length>0;$('studentbody').innerHTML=state.students.map(s=>'<tr class="clickrow studentrow" data-id="'+esc(s.id)+'" tabindex="0"><td><div class="person">'+esc(s.firstName+' '+s.lastName)+'</div><div class="secondaryline">'+esc(s.studentId)+'</div></td><td>'+esc(s.grade||'—')+'</td><td class="mono">'+esc(s.barcode)+'</td><td>'+esc(s.visitCount)+'</td><td>'+esc(fdt(s.lastVisitAt))+'</td><td><span class="status '+(s.active?'ok':'')+'">'+(s.active?'Active':'Inactive')+'</span></td><td style="color:var(--quiet);font-size:17px">›</td></tr>').join('');const a=state.studentTotal?state.studentOffset+1:0,b=Math.min(state.studentOffset+state.students.length,state.studentTotal);$('studentpage').textContent=a+'–'+b+' of '+state.studentTotal;$('studentprev').disabled=state.studentOffset===0;$('studentnext').disabled=state.studentOffset+state.pageSize>=state.studentTotal}catch(e){toast(e.message)}}
function openDrawer(){$('drawer').classList.add('open');$('scrim').classList.add('open')}function closeDrawer(){$('drawer').classList.remove('open');$('scrim').classList.remove('open');state.student=null}
async function studentDetail(id){openDrawer();$('drawertitle').textContent='Loading…';$('drawersub').textContent='';$('drawerview').hidden=false;$('studentform').classList.remove('open');$('editbtn').hidden=true;$('savebtn').hidden=true;$('canceledit').hidden=true;try{const d=await api('/api/library/admin-student?id='+encodeURIComponent(id));state.student=d.student;state.studentVisits=d.recentVisits||[];renderDrawer()}catch(e){toast(e.message);closeDrawer()}}
function renderDrawer(){const s=state.student;$('drawertitle').textContent=s.firstName+' '+s.lastName;$('drawersub').textContent='Student ID '+s.studentId;$('dgrade').textContent=s.grade||'Not set';$('dstatus').innerHTML='<span class="status '+(s.active?'ok':'')+'">'+(s.active?'Active':'Inactive')+'</span>';$('dbarcode').textContent=s.barcode;$('dvisits').textContent=s.visitCount;$('drecent').innerHTML=state.studentVisits.length?state.studentVisits.map(v=>'<div class="item"><div><div class="itemname">'+esc(v.reason)+'</div><div class="itemsub">'+esc(fdt(v.checkedInAt)+(v.checkedOutAt?' · '+dur(v.durationMinutes):' · Still in library'))+'</div></div></div>').join(''):'<div class="itemsub">No library visits yet.</div>';$('drawerview').hidden=false;$('studentform').classList.remove('open');$('editbtn').hidden=false;$('savebtn').hidden=true;$('canceledit').hidden=true}
function fillForm(s){$('studentform').reset();$('editid').value=s?s.id:'';$('sid').value=s?s.studentId:'';$('sid').disabled=!!s;$('first').value=s?s.firstName:'';$('last').value=s?s.lastName:'';$('barcode').value=s?s.barcode:'';$('editgrade').value=s&&s.grade?s.grade:'';$('active').checked=s?s.active:true}
function startEdit(){fillForm(state.student);$('drawerview').hidden=true;$('studentform').classList.add('open');$('editbtn').hidden=true;$('savebtn').hidden=false;$('canceledit').hidden=false}
function newStudent(){state.student=null;openDrawer();$('drawertitle').textContent='Add student';$('drawersub').textContent='Create a library student record';fillForm(null);$('drawerview').hidden=true;$('studentform').classList.add('open');$('editbtn').hidden=true;$('savebtn').hidden=false;$('canceledit').hidden=false;setTimeout(()=>$('sid').focus(),0)}
async function saveStudent(){if(!$('studentform').reportValidity())return;const body={id:Number($('editid').value||0),studentId:$('sid').value.trim(),firstName:$('first').value.trim(),lastName:$('last').value.trim(),barcode:$('barcode').value.trim(),grade:$('editgrade').value,active:$('active').checked};$('savebtn').disabled=true;try{const r=await post('/api/library/admin-students',body);toast(body.id?'Student updated.':'Student added.');await loadStudents();if(r.id)await studentDetail(r.id);else closeDrawer();loadOverview()}catch(e){toast(e.message)}finally{$('savebtn').disabled=false}}
function localDate(d){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),m={};p.forEach(x=>m[x.type]=x.value);return m.year+'-'+m.month+'-'+m.day}
function setDates(){const p=$('period').value,t=localDate(new Date());if(p==='custom'){$('fromfield').hidden=false;$('tofield').hidden=false;if(!$('from').value)$('from').value=t;if(!$('to').value)$('to').value=t;return}$('fromfield').hidden=true;$('tofield').hidden=true;const days=p==='30'?29:p==='7'?6:0;$('from').value=localDate(new Date(Date.now()-days*86400000));$('to').value=t}
function historyArchived(){return $('archivedview').value==='1'}
function archivePrompt(id,archive){const v=state.history.find(x=>String(x.visitId)===String(id));if(!v)return;const who=v.firstName+' '+v.lastName;if(!archive){confirmDo('Restore visit','Put this '+who+' visit back into history, stats and exports.','Restore',async()=>{await post('/api/library/admin-archive-visit',{visitId:v.visitId,archived:false});toast('Visit restored.');await loadHistory();loadOverview()});return}
const stillIn=!v.checkedOutAt;confirmDo('Archive visit','Hide this '+who+' visit from history, stats and exports. You can restore it from the archived view.'+(stillIn?' This visit has no checkout, so archiving will also close it.':''),'Archive',async()=>{await post('/api/library/admin-archive-visit',{visitId:v.visitId,archived:true});toast('Visit archived.');await loadHistory();loadOverview()})}
function historyQuery(){const p=new URLSearchParams({limit:String(state.pageSize),offset:String(state.historyOffset)}),q=$('historysearch').value.trim(),r=$('reason').value;if(q)p.set('q',q);if(r)p.set('reason',r);if($('from').value)p.set('from',$('from').value);if($('to').value)p.set('to',$('to').value);if(historyArchived())p.set('archived','1');return p}
async function loadHistory(){setDates();const archived=historyArchived();try{const d=await api('/api/library/admin-history?'+historyQuery());state.history=d.visits||[];state.historyTotal=d.total||0;$('historynote').textContent=state.historyTotal+(archived?' archived visit':' visit')+(state.historyTotal===1?'':'s')+' in this view';$('historyemptytitle').textContent=archived?'No archived visits.':'No visits found.';$('historyemptycopy').textContent=archived?'Records you archive from this tab appear here.':'Change the date range or filters.';$('historyempty').hidden=state.history.length>0;$('historybody').innerHTML=state.history.map(v=>'<tr><td><div class="person">'+esc(v.firstName+' '+v.lastName)+'</div><div class="secondaryline">'+esc(v.studentId)+(v.archivedAt?' · archived '+esc(fdt(v.archivedAt)):'')+'</div></td><td>'+esc(v.reason)+'</td><td class="mono">'+esc(fdt(v.checkedInAt))+'</td><td class="mono">'+esc(fdt(v.checkedOutAt))+'</td><td>'+esc(dur(v.durationMinutes))+'</td><td>'+(v.checkedOutAt?esc({scan_out:'Scanned out',librarian:'Librarian',clear_all:'Cleared',auto_end_of_day:'End of day'}[v.checkoutMethod]||'Checked out'):'<span class="status ok">Still in</span>')+'</td><td class="rowaction"><button class="btn secondary small" data-archive="'+v.visitId+'" data-mode="'+(archived?'restore':'archive')+'">'+(archived?'Restore':'Archive')+'</button></td></tr>').join('');const a=state.historyTotal?state.historyOffset+1:0,b=Math.min(state.historyOffset+state.history.length,state.historyTotal);$('historypage').textContent=a+'–'+b+' of '+state.historyTotal;$('historyprev').disabled=state.historyOffset===0;$('historynext').disabled=state.historyOffset+state.pageSize>=state.historyTotal}catch(e){toast(e.message)}}
async function loadKiosks(){try{const d=await api('/api/library/kiosk-devices'),rows=d.devices||[],active=rows.filter(x=>!x.revokedAt);$('kiosknote').textContent=active.length+' active paired device'+(active.length===1?'':'s');$('kioskempty').hidden=rows.length>0;$('kiosklist').innerHTML=rows.map(k=>{const seen=k.lastSeenAt?new Date(k.lastSeenAt).getTime():0,online=!k.revokedAt&&seen&&Date.now()-seen<600000,status=k.revokedAt?['','Revoked']:online?['ok','Online']:['warns','Offline'],meta=k.revokedAt?'Revoked '+fdt(k.revokedAt):'Last seen '+ago(k.lastSeenAt)+' · Paired '+fdt(k.createdAt);return'<div class="device"><div><div class="devname">'+esc(k.name)+'</div><div class="devmeta">'+esc(meta)+'</div></div><div class="devactions"><span class="status '+status[0]+'">'+status[1]+'</span>'+(k.revokedAt?'':'<button class="btn dangerquiet small revoke" data-id="'+esc(k.id)+'" data-name="'+esc(k.name)+'">Revoke</button>')+'</div></div>'}).join('')}catch(e){toast(e.message)}}
function pairOpen(){clearInterval(state.pairTimer);$('pairstart').hidden=false;$('pairresult').hidden=true;$('generate').hidden=false;$('pairdone').hidden=true;$('paircancel').hidden=false;$('kioskname').value='';$('pairmodal').classList.add('open');setTimeout(()=>$('kioskname').focus(),0)}function pairClose(){clearInterval(state.pairTimer);$('pairmodal').classList.remove('open')}
async function pairGenerate(){const name=$('kioskname').value.trim();if(!name){toast('Enter a device name first.');return}$('generate').disabled=true;try{const d=await post('/api/library/kiosk-pairing',{name});$('paircode').textContent=String(d.pin||'').replace(/(\d{4})(\d{4})/,'$1 $2');state.pairExpiry=new Date(d.expiresAt).getTime();$('pairstart').hidden=true;$('pairresult').hidden=false;$('generate').hidden=true;$('paircancel').hidden=true;$('pairdone').hidden=false;pairTick();state.pairTimer=setInterval(pairTick,1000);loadKiosks()}catch(e){toast(e.message)}finally{$('generate').disabled=false}}
function pairTick(){const s=Math.max(0,Math.floor((state.pairExpiry-Date.now())/1000));$('pairexp').textContent=s?'Expires in '+Math.floor(s/60)+':'+String(s%60).padStart(2,'0'):'This code has expired';if(!s)clearInterval(state.pairTimer)}
function confirmDo(title,copy,label,fn){state.confirm=fn;$('confirmtitle').textContent=title;$('confirmcopy').textContent=copy;$('confirmaction').textContent=label;$('confirmmodal').classList.add('open')}function confirmClose(){state.confirm=null;$('confirmmodal').classList.remove('open')}async function runConfirm(){if(!state.confirm)return;$('confirmaction').disabled=true;try{await state.confirm();confirmClose()}catch(e){toast(e.message)}finally{$('confirmaction').disabled=false}}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.body.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)setPage(g.dataset.go)});
$('refresh').onclick=()=>loadPage(state.page);$('currentsearch').oninput=renderCurrent;$('more').onclick=e=>{e.stopPropagation();$('moremenu').classList.toggle('open')};document.addEventListener('click',()=> $('moremenu').classList.remove('open'));$('openkiosk').onclick=()=>window.open('/library/kiosk','_blank','noopener');
$('clearall').onclick=()=>confirmDo('Check everyone out?','This will check out every student who is currently in the library. Use this at closing time or when the live roster needs to be cleared.','Check everyone out',async()=>{await post('/api/library/clear',{method:'clear_all'});toast('Everyone was checked out.');await loadCurrent();loadOverview()});
$('currentbody').onclick=async e=>{const b=e.target.closest('.checkout');if(!b)return;b.disabled=true;try{await post('/api/library/checkout',{visitId:Number(b.dataset.id),method:'librarian'});await loadCurrent()}catch(x){b.disabled=false;toast(x.message)}};
['studentsearch','studentgrade','studentstatus'].forEach(id=>$(id).addEventListener(id==='studentsearch'?'input':'change',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.studentOffset=0;loadStudents()},180)}));$('studentprev').onclick=()=>{state.studentOffset=Math.max(0,state.studentOffset-state.pageSize);loadStudents()};$('studentnext').onclick=()=>{state.studentOffset+=state.pageSize;loadStudents()};$('addstudent').onclick=newStudent;$('studentbody').onclick=e=>{const r=e.target.closest('.studentrow');if(r)studentDetail(r.dataset.id)};$('studentbody').onkeydown=e=>{const r=e.target.closest('.studentrow');if(r&&(e.key==='Enter'||e.key===' ')){e.preventDefault();studentDetail(r.dataset.id)}};
$('drawerclose').onclick=closeDrawer;$('scrim').onclick=closeDrawer;$('editbtn').onclick=startEdit;$('canceledit').onclick=()=>state.student?renderDrawer():closeDrawer;$('savebtn').onclick=saveStudent;
$('historysearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.historyOffset=0;loadHistory()},180)};$('period').onchange=()=>{state.historyOffset=0;setDates();loadHistory()};$('archivedview').onchange=()=>{state.historyOffset=0;loadHistory()};$('historybody').onclick=e=>{const b=e.target.closest('[data-archive]');if(b)archivePrompt(b.dataset.archive,b.dataset.mode==='archive')};$('filterbtn').onclick=()=>$('filters').classList.toggle('open');['reason','from','to'].forEach(id=>$(id).onchange=()=>{state.historyOffset=0;loadHistory()});$('historyprev').onclick=()=>{state.historyOffset=Math.max(0,state.historyOffset-state.pageSize);loadHistory()};$('historynext').onclick=()=>{state.historyOffset+=state.pageSize;loadHistory()};$('exportbtn').onclick=()=>{setDates();const p=new URLSearchParams();if($('from').value)p.set('from',$('from').value);if($('to').value)p.set('to',$('to').value);location.href='/api/library/export-csv?'+p};
$('pairbtn').onclick=pairOpen;$('pairclose').onclick=pairClose;$('paircancel').onclick=pairClose;$('pairdone').onclick=pairClose;$('generate').onclick=pairGenerate;$('pairmodal').onclick=e=>{if(e.target===$('pairmodal'))pairClose()};
$('kiosklist').onclick=e=>{const b=e.target.closest('.revoke');if(!b)return;confirmDo('Revoke '+(b.dataset.name||'this kiosk')+'?','This device will stop being able to use the kiosk and will need a new pairing code before it can connect again.','Revoke kiosk',async()=>{await post('/api/library/kiosk-revoke',{deviceId:Number(b.dataset.id)});toast('Kiosk revoked.');await loadKiosks();loadOverview()})};
$('confirmclose').onclick=confirmClose;$('confirmcancel').onclick=confirmClose;$('confirmaction').onclick=runConfirm;$('confirmmodal').onclick=e=>{if(e.target===$('confirmmodal'))confirmClose()};
document.onkeydown=e=>{if(e.key!=='Escape')return;$('moremenu').classList.remove('open');if($('confirmmodal').classList.contains('open'))confirmClose();else if($('pairmodal').classList.contains('open'))pairClose();else if($('drawer').classList.contains('open'))closeDrawer()};
setDates();setPage(pages[location.hash.slice(1)]?location.hash.slice(1):'current');setInterval(renderUpdated,5000);setInterval(()=>{if(state.page==='current')loadCurrent();else if(state.page==='overview')loadOverview()},10000);
</script>
</body>
</html>`;
}
